apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.fullname" . }}-config
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}